openapi: 3.0.0
info:
  title: Tom's Awesome API
  description: Just doing awesome stuff!
  version: 1.0.0

servers:
  - url: http://api.toms-awesome-stuff.example.com/
    description: Production
paths:
  /stuff:
    get:
      summary: Get all the awesome stuff
      responses:
        200:
          description: A JSON array of awesome stuff
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Brilliance
